telus-agcg/nib

bin/update
This fixes a bug introduced by a previous PR: https://github.com/technekes/nib/pull/18
=> Adds a method to run the (pull) update with native compose

README.md
This repo is now public and no longer requires a  #"login" to the technekes
organization for pulling the image.
=> Corrects update instructions

release.sh
This allows for the "latest" tag on the Docker hub to reflect the most
recently released commit.
=> Tag current commit as latest during releaes

Dockerfile, bin/_help
In the case that a user asks for help, take the opprotunity to ensure
they're running the latest version of `nib`. This also corrects a
problem where the `--version` command was not working because the
`VERSION` file was not mounted into the image.
@johnallen3d :eyes:
=> Add version update warning and correct version command

bin/console
Pry uses a seperate rc file (pryrc) from IRB. This adds the concept of a
pryrc and points it history file path at the existing irb history file.
=> Add Pry history to `console` command

bin/_help
Before this change when searching the `$COMMANDS` array for something like the command "run" several results came back because it's a commonly used word. With this change in place we are now searching for "run|".
=> Tighten up command help grep

README.md, bin/_common, bin/_help, bin/debug
The primary reason for the `.nib` file currently is for the debug command. This change uses a tool to convert the `docker-compose.yml` into JSON which is then parsable by `jq`.
Resolves #38
=> Remove the need for the `.nib` file

Dockerfile, bin/bundle, bin/guard, bin/nib, bin/rails, bin/rake, bin/rspec, bin/rubocop, bin/wrap_command, config/commands.json
Added a config file that contains the supported commands, their description and whether or not they are simple "wrapped" commands. With this data we can simply detect if a command like `bundle` is a wrapped command and execute `bin/wrap_command` rather than having a duplicative script for each.
This would be a good start for addressing #39.
=> Use commands config to execute wrapper commands

bin/nib
The previous logic was testing for a file in ./bin that matched the command name. The setup has changed for "wrapped" commands therefore the logic needs altering as well.
=> Allow wrapped commands to work

.dockerignore, Dockerfile, Dockerfile.test, spec/localhost/yaml2json_spec.rb
The yaml2json library is a requirement for the debug command to work but was never added to the repo/image :blush:. This commit adds it at build time to the Docker image.
=> Install yaml2json at build time for debug command

bin/_help, bin/_tty, config/commands.json, docs/commands.md, update_docs.sh
Commands like `console` and `setup` support overrides and hooks. In order to make that more clear this commit adds a `.long_description` field to `./config/commands.json` and exposes that in the command specific help (ie. `nib console --help`).
After this change help for `console` and `setup` render as such:
```
❯ nibdev console --help
Usage: nib console [SERVICE]
Start a REPL session for the given service
This command will try to detect the applications environment (ie. rails console or bundle console)
and start the most appropriate REPL possible. It's possible to directly override this behaviour by
supplying an executable file at $pwd/bin/console.
Options:
-e, --env   Environment name (default: development)
-h          Print usage
Services:
- app
```
```
❯ nibdev setup --help
Usage: nib …
```
=> Add additional description for complex commands

bin/_common, bin/_help, bin/nib, bin/setup, config/commands.json
~~In addition to supporting this new option (minor)~~ (change removed) this commit adds support for defining options in configuration and having them rendered in help.
* New based on comments below:
The additional arguments to the setup command are now passed through to each of the setup scripts.
=> Add options support; Pass arguments to setup binstubs.

bin/_tty, bin/console
Allows for applications to have a WORKDIR other than  /usr/src/app and still support shell/console history.
Resolves #78
=> Do not expect WORKDIR /usr/src/app

bin/nib
When we are calling compose we want to completely turn over execution
over. Kernel.exec replaces the current (Ruby) process with the executed
command.
Resolves #85
Resolves #86
=> Use Kernel.exec when delegating to compose

lib/nib/command.rb, spec/unit/console_spec.rb, spec/unit/shell_spec.rb, spec/unit/update_spec.rb
Whenever we delegate to compose we want it to take over the process and respond to signals like SIGTERM.
This is a continuation of #87
=> Always use Kernel.exec for compose delegation

bin/nib, lib/nib/code_climate.rb, lib/nib/debug.rb, spec/unit/debug_spec.rb
This change was [previously made](https://github.com/technekes/nib/commit/abfd9e33e9ee24eb954704aeffd86095ecc5b4c5) however was lost in the transition from bash to Ruby.
Resolves #74
=> Viva the `--no-deps` switch

lib/nib/options.rb, lib/nib/options/parser.rb, spec/unit/options/augmenter_spec.rb, spec/unit/options/parser_spec.rb
Prior to this implementation something like the following was not possible:
```sh
nib run -e RAILS_ENV=production web puma
```
These changes add support for accepting the remaining options (flags) for the `exec` and `run` commands specifically.
Help output for `exec` and `run` now looks like this:
```sh
❯ nibdev exec --help
NAME
exec - Attach an interactive shell session to a running container
SYNOPSIS
nib [global options] exec [command options] service [command][, [command]]*
COMMAND OPTIONS
-T            - Disable pseudo-tty allocation. By default `docker-compose run` allocates a TTY.
-d            - Detached mode: Run container in the background, print new container name.
--index=index - index of the container if there are multiple instances of a service [default: 1] (default: none) …
```
=> Support passing through flags for exec/run

bin/nib
This will allow for passing alternative config to delegated commands:
```sh
nib -f docker-compose.alt.yml up
```
This change does not allow for `-f` to be passed to "native" `nib`
commands (`shell`, `console` etc.)
=> Add support for `-f` flag

Rakefile, codeship-steps.yml, nib.gemspec
There were some difficulties with the CodeClimate gem running on Codeship which previously required a patch. v1.0.5 of the gem should resolve this issue.
=> Re-enable CodeClimate coverage reporting

bin/nib
Prior to this change whether the `--no-deps` flag was specified or not it was always evaluated by `gli` to be `false` and therefor never sent on to `docker-compose`. For more details on why, have a look at this issue report on `gli`. https://github.com/davetron5000/gli/pull/90
Resolves #97
=> Allow `--no-deps` on `run` to behave as expected

lib/nib.rb, lib/nib/console.rb, lib/nib/exec.rb, lib/nib/history.rb, lib/nib/run.rb, lib/nib/shell.rb, spec/unit/console_spec.rb, spec/unit/run_spec.rb, spec/unit/shell_spec.rb
Previously the shell and console command set up "shell history" and the console command setup "irb/pry history". However, if you were to execute the shell command and then `> pry` the pry history would not be wired up. With this change any interactive session is prepped with all history types configured.
Resolves #100
=> Make history more universal

Rakefile, bin/ci, codeship-steps.yml
Test coverage reporting has not been working. Having reviewed the output on Codeship it would appear that the reporter is running in a container other than then the container that generates the coverage. This change ensure they are run together.
=> Report test coverage in spec container

CHANGELOG.md, Dockerfile, bin/update_docs, lib/nib/check_for_update.rb, lib/nib/code_climate.rb, lib/nib/command.rb, lib/nib/console.rb, lib/nib/debug.rb, lib/nib/exec.rb, lib/nib/history.rb, lib/nib/setup.rb, lib/nib/shell.rb, lib/nib/unrecognized_help.rb, nib.gemspec, spec/unit/debug_spec.rb
Removes syntax sugar usage introduced since Ruby version 2.2
Resolves #118
=> Support prior versions or Ruby

nib.gemspec
A recent release will (hopefully) fix issues with reporting test coverage from Codeship.
https://github.com/codeclimate/ruby-test-reporter/pull/172
=> Use latest version of code-climate-test-reporter

CHANGELOG.md, lib/nib/history.rb, lib/nib/run.rb, spec/unit/run_spec.rb
The introduction of history to the `run` command introduced a regression where if an argument was not passed to `run` the container would exit immediately. Now the `run` command will check to see if a command is specified and only hook up history if so.
Resolves #127
=> Use CMD if argument not passed to `run`

Dockerfile, bin/ci, bin/release, spec/dummy/rails/bin/setup, spec/dummy/rails/bin/setup.after.stub, spec/dummy/rails/bin/setup.before.stub, spec/integration/bundle_spec.rb, spec/integration/codeclimate_spec.rb, spec/integration/console_spec.rb, spec/integration/debug_spec.rb, spec/integration/exec_spec.rb, spec/integration/guard_spec.rb, spec/integration/rails_spec.rb, spec/integration/rake_spec.rb, spec/integration/rspec_spec.rb, spec/integration/rubocop_spec.rb, spec/integration/run_spec.rb, spec/integration/setup_spec.rb, spec/integration/shell_spec.rb, spec/serverspec_helper.rb
Switches back to an Alpine based image for dev/ci. The result is from an 800+mb image down to 74mb and the image builds in ~1min.
Some notes:
* The currently available version of Ruby on APK is 2.3.3. This is an upgrade from what we were previously using (2.2.x). The reason we were using 2.2 was we wanted the gem to be backward compatible to that version.
* Previously integration specs were relying on `nib` to be available on the PATH. This is not the case in this image (not sure why) so I've edited the integration specs to point to `/usr/src/app/bin/nib` via a constant (`NIB_BIN`).
=> Viva la Alpine image!

CHANGELOG.md, lib/nib.rb, lib/nib/code_climate.rb, lib/nib/command.rb, lib/nib/history.rb, lib/nib/history/compose.rb, lib/nib/history/config.rb, spec/fixtures/compose/with_existing_volumes_key.yml, spec/fixtures/compose/without_existing_volumes_key.yml, spec/support/setup.rb, spec/unit/history/compose_spec.rb
Previously we used `./tmp` which worked for most cases however:
* If a project did not `gitignore` the `./tmp` folder users would see unexpected files in there diff (ie. `./tmp/shell_history`)
* Some users are running containers on an external machine and are not able to bind mount the local directory into the container.
This code now creates a history volume per project, mounts that new volume into each service (at `/usr/local/history`) and writes history files to it.
=> Use a Docker volume to store history

lib/nib/history/compose.rb, spec/fixtures/compose/with_a_literal_dollar.yml, spec/support/setup.rb, spec/unit/history/compose_spec.rb
In situations where `$` is present in the result of `docker-compose config` we need to escape because we are recreating a `docker-compose.yml`. If not `docker-compose` is attempting variable substitution.
Resolves #134
=> Handle `$` in docker-compose config

Dockerfile
In order to run the `rake release` task two additional dependencies need to be present in the container that we are building.
=> Support running `rake release`

nib.gemspec
This will make the Gemnasium badge happy
=> Allow the `gli` dependency to float minor versions

bin/nib
For commands not handled by `nib` this will ensure that the special "history volume" is in place. This is helpful for the scenario where the user does a `nib up -d && nib exec web`.
Resolves #144
=> Add history volume for delegated commands

.rubocop.yml, lib/nib/command.rb, lib/nib/history.rb, lib/nib/shell.rb, spec/unit/shell_spec.rb
The new and improved `shell` command will now generate a statement that looks like this:
```sh
docker-compose \
-f /tmp/nib/compose20170605-237-1y7p1o1 \
run \
--rm \
--entrypoint='
/bin/sh -c "
export HISTFILE=/usr/local/history/shell_history
cp /tmp/nib/config/irbrc /root/.irbrc 2>/dev/null
cp /tmp/nib/config/pryrc /root/.pryrc 2>/dev/null
if [ -f bin/shell ]; then bin/shell;
elif hash zsh 2>/dev/null ; then zsh;
elif hash bash 2>/dev/null ; then bash;
elif hash ash 2>/dev/null ; then ash;
else sh; fi
"
' \
web \
/bin/sh -c "
export HISTFILE=/usr/local/history/shell_history
cp /tmp/nib/config/irbrc /root/.irbrc 2>/dev/null
cp /tmp/nib/config/pryrc /root/.pryrc 2>/dev/null
"
```
Not that the trailing "`CMD`" will be completely ignored because the `ENTRYPOINT` does not accept arguments. I …
=> Support images with an ENTRYPOINT for `shell` command

lib/core_extensions/string.rb, lib/nib.rb, lib/nib/check_for_update.rb, lib/nib/unrecognized_help.rb
A change to make nib work with Ruby 2.2 (16cc0bf07683fa0833c3a8677f437ea0e7ac6011) removed the "squiggly heredoc" syntax but did not account for the fact that printed heredocs would now be indented.
=> Strip indentation from heredocs

bin/nib, lib/nib.rb, lib/nib/plugin.rb, lib/nib/plugins.rb, spec/unit/nib_spec.rb
Now when a user asks for "help" the list of plugins that are installed will be printed.
Example output:
```
...
shell       - Start a shell session in a one-off service container
update      - Download the latest version of nib
Installed plugins:
- nib-crypt
- nib-heroku
- nib-ruby
Note:
Unrecognized commands will be delegated to docker-compose.
...
```
=> Print a list of installed plugins with help

.rubocop.yml, lib/core_extensions/psych.rb, lib/nib.rb, lib/nib/debug.rb, lib/nib/history/compose.rb, lib/nib/options.rb
The API for the version of Psych that ships with currently supported versions of Ruby (2.7, 3.0, 3.1) are slightly different when it comes to loading potentially "unsafe" YAML content. Rather than forcing users to the latest version this monkey-patch tries do deal with these inconsistencies in a natural way.
Fixes #168
=> Handle varied Psych load API's

.github/workflows/lint_and_test.yml
The modified steps are running in a matrix for three different versions of Ruby. There's no need to do these following steps more than once:
- lint: Ruby version doesn't impact linting rules
- upload artifact: only need one copy
- report coverage: coverage won't change from version to version
=> ci: only lint and report coverage once
